import "@radix-ui/themes/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <NavBar />
<<<<<<< HEAD
          <main className="p-5">{children}</main>
=======
          <main>{children}</main>
>>>>>>> a60c6a5325b9075ccf643c253c86c91f4cf40c3a
        </Theme>
      </body>
    </html>
  );
}
