import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import QueryClientProvider from "./QueryClientProvider";
import AuthProvider from "./auth/Provider";
import "./globals.css";
import "./theme-config.css";
// @ts-ignore
import getRandomQuote from "amazing-quotes"

const quote = getRandomQuote();

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme accentColor="violet">
              <NavBar />
              <main className="p-5">
                <Container>{children}</Container>
              </main>
             <Container className="max-w-4xl mx-auto my-8 bg-white rounded-none shadow-md overflow-hidden">
  <div className="flex">
    <div className="w-2 bg-[#6e56cf]"></div>
    <div className="flex-1 p-8 sm:p-12">
      <div className="mb-6">
        <svg className="w-10 h-10 text-[#6e56cf]" fill="currentColor" viewBox="0 0 24 24">
          <path d="M14.017 21v-7.391c0-5.704 3.731-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h4v10h-9.983zm-14.017 0v-7.391c0-5.704 3.748-9.57 9-10.609l.996 2.151c-2.433.917-3.996 3.638-3.996 5.849h3.983v10h-9.983z"/>
        </svg>
      </div>
      <blockquote className="mb-8">
        <p className="text-xl sm:text-2xl font-light leading-relaxed text-gray-800">{quote.text}</p>
      </blockquote>
      <cite className="block text-right">
        <span className="font-semibold text-gray-900 not-italic"> - {quote.author}</span>
      </cite>
    </div>
  </div>
</Container>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
